
server:
    port: 9999

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/pizza-db?useSSL=false
        username: pizza-user
        password: pizza-pass
